In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("StudentsPerformance.csv")

In [6]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [7]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [8]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 103.5 KB

In [10]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [11]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.shape

(1000, 8)

In [14]:
categarical_columns=["gender","race/ethnicity","parental level of education","lunch","test preparation course"]

In [15]:
for column in categarical_columns:
    df[column]=df[column].astype(str).str.strip().str.lower()

In [16]:
df[column]

0           none
1      completed
2           none
3           none
4           none
         ...
995    completed
996         none
997    completed
998    completed
999         none
Name: test preparation course, Length: 1000, dtype: str

In [17]:
score_columns=["math score","reading score","writing score"]

In [18]:
for columns in score_columns:
   mean=df[columns].mean()
   median=df[columns].median()
   mode=(df[columns].mode()[0])

In [19]:
print("mean_score=",mean)
print("median_score=",median)
print("mode_score=",mode)

mean_score= 68.054
median_score= 69.0
mode_score= 74

In [20]:
for columns in score_columns:
    mean=df[columns].mean()
    median=df[columns].median()
    mode=df[columns].mode()
    std=df[columns].std()
    Q1=df[columns].quantile(0.25)
    Q3=df[columns].quantile(0.75)
    print("mean:",mean)
    print("median:",median)
    print("mode:",mode)
    print("Q1:",Q1)
    print("Q3:",Q3)

mean: 66.089
median: 66.0
mode: 0    65
Name: math score, dtype: int64
Q1: 57.0
Q3: 77.0
mean: 69.169
median: 70.0
mode: 0    72
Name: reading score, dtype: int64
Q1: 59.0
Q3: 79.0
mean: 68.054
median: 69.0
mode: 0    74
Name: writing score, dtype: int64
Q1: 57.75
Q3: 79.0

In [21]:
for columns in ["math score","reading score","writing score"]:
    IQR = Q3-Q1
    LOWER=Q1-1.5*IQR
    UPPER=Q3+1.5*IQR
    OUTLIERS=df[
        (df[columns]<LOWER) |
        (df[columns]>UPPER)]
    print("outliers in",columns)
    print(OUTLIERS[columns])

outliers in math score
17     18
59      0
145    22
338    24
787    19
842    23
980     8
Name: math score, dtype: int64
outliers in reading score
59     17
327    23
596    24
980    24
Name: reading score, dtype: int64
outliers in writing score
59     10
76     22
327    19
596    15
980    23
Name: writing score, dtype: int64

In [22]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Percentage": [95, 82, 65, 52, 40]
}

df = pd.DataFrame(data)

def get_performance(percentage):
    if percentage >= 90:
        return "Excellent"
    elif percentage >= 75:
        return "Very Good"
    elif percentage >= 60:
        return "Good"
    elif percentage >= 50:
        return "Average"
    else:
        return "Needs Improvement"

df["Performance"] = df["Percentage"].apply(get_performance)

print(df[["Percentage", "Performance"]])

   Percentage        Performance
0          95          Excellent
1          82          Very Good
2          65               Good
3          52            Average
4          40  Needs Improvement

In [26]:
import pandas as pd

df = pd.DataFrame({
    "Math": [85, 90],
    "Science": [80, 95],
    "English": [75, 85]
})

score_columns = ["Math", "Science", "English"]

df["total marks"] = df[score_columns].sum(axis=1, numeric_only=True)

print(df)

   Math  Science  English  total marks
0    85       80       75          240
1    90       95       85          270

In [27]:
df["Percentage"] = (df["total marks"] / 300) * 100

In [28]:
import pandas as pd

df = pd.DataFrame({
    "Math": [85, 90],
    "Science": [80, 95],
    "total marks": [165, 185],
    "Percentage": [82.5, 92.5]
})

score_columns = ["Math", "Science"]

print(df[score_columns + ["total marks", "Percentage"]])

   Math  Science  total marks  Percentage
0    85       80          165        82.5
1    90       95          185        92.5

In [29]:
df.to_csv("cleaned_student_performance.csv", index=False)

In [30]:
df

   Math  Science  total marks  Percentage
0    85       80          165        82.5
1    90       95          185        92.5